name: Dependabot auto-merge
run-name: Merging PR ${{ github.event.workflow_run.pull_requests[0].number }}
on:
  workflow_run:
    branches:
      - dependabot/**
    types:
      - completed
    workflows:
      - "Continuous integration"

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v5.0.1
      - name: Enable auto-merge for Dependabot PRs
        env:
          PR_URL: ${{ github.event.workflow_run.pull_requests[0].number }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase "$PR_URL"
